### ISSUE TITLE
회사 영문 표기

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#37]
주식회사, 법인 등 회사의 종류에 따라 표기가 달라지는데 75mm-studio는 어떤회사인가요?

**Comment by khw7096** [comment]
한국 공식명이 `75미리스튜디오(주)` 인데.. 대표님에게 물어볼께요.

주식관련 이야기를 한적이 없거든요. 이슈는 회사 Slack 에 던져놨어요.

**Comment by khw7096** [comment]
서영님 만약 답글이 없다면 일단, 법인으로 표기하고 주식회사 표기는 따로 댓글로 남겨두어서 나중에 이 이슈가 나오면 rg명령어로 검색하고 고칠 수 있도록 해요~

**Comment by khw7096** [comment]
75mm Studio Co.,Ltd.

영문표기명 입니다. nda.md 파일을 수정할 때 참고해주세요. 형태는 유한책임법인 입니다.

**Comment by baesy0** [comment]
네 확인했어요!

**Comment by khw7096** [comment]
이 이슈는 닫을께요.

README.md 상단에도 적어두었어요 해깔리면 확인해용~
