### ISSUE TITLE
법령이름 오타인가요?

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#43]
기밀유지 협약의 [위약벌 또는 손해배상액의 예정](https://github.com/75mm-studio/security/blob/master/docs/nda.md#%EC%9C%84%EC%95%BD%EB%B2%8C-%EB%98%90%EB%8A%94-%EC%86%90%ED%95%B4%EB%B0%B0%EC%83%81%EC%95%A1%EC%9D%98-%EC%98%88%EC%A0%95) 부분에서 "정보통신망이용촉진 및 법률" 과 일치하는 이름의 법령이 존재하지 않는데 혹시 "정보통신망이용촉진 및 정보보호등에 관한 법률"의 오타인가요?
```
보안사항을 위반하였을 경우에는 문제의 경중을 논하여 "부정경쟁방지 및 영업비밀보호에 관한 법률", "정보통신망이용촉진 및 법률" 등 관련법령에 의한 민·형사상의 책임 이외에도, 회사에 끼친 손해에 대해 변상을 회사가 요구할 수 있습니다.
```

**Comment by khw7096** [comment]
http://www.law.go.kr/lsInfoP.do?lsiSeq=111970#0000

이 항목들이예요.

**Comment by khw7096** [comment]
https://github.com/75mm-studio/security/pull/44

의문점을 표기한걸 표기해서 PR올렸어요.

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/55040281-0c530180-506b-11e9-8716-6b266411db32.png)

**Comment by baesy0** [comment]
+4!

**Comment by khw7096** [comment]
pr 머지했어요. 이 이슈는 닫을께요.
