### ISSUE TITLE
CCTV화면을 볼 수 있는 권한이 있는 사람은 누구인지 특정짓는 것이 좋을 거 같아요

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#49]
[네트워크/서버 문서](https://github.com/75mm-studio/security/blob/master/docs/network.md#%EC%84%9C%EB%B2%84%EC%A0%91%EA%B7%BC)에서 CCTV 화면을 볼 수 있는 권한이 있는 사람을 특정짓는 게 좋을 것 같아요.
##### 현재 내용
```
CCTV 녹화중, 어플리케이션을 이용하여 핸드폰으로 실시간 확인 가능합니다.
```

**Comment by khw7096** [comment]
보안관리자(정) 이라고 써둘께요

**Comment by khw7096** [comment]
작성완료. 이 이슈를 닫습니다.
