### ISSUE TITLE
Code Name 문서관련 질문

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#50]
1. [코드네임문서](https://github.com/baesy0/security/blob/codeName/docs/codename.md#%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8%ED%9A%8C%EC%82%ACclient-company)에서 '접근사용자'의 개념을 알려주세요. 혹은 접근사용자를 지칭하는 영어가 따로 있나요? 검색을 해도 잘 안나와요.

1.
```
데이터베이스 역시 프로젝트 코드네임을 관리 및 사용합니다.
```
데이터베이스를 통해 프로젝트의 코드네임을 관리한다. + 데이터베이스에도 코드네임이 부여된다.
로 해석하면 될까요?

**Comment by khw7096** [comment]
이 부분은 좀더 설명을 풀어서 git pull 해둘께요.

**Comment by khw7096** [comment]
2번에 걸쳐서 문장이 수정되었어요.

https://github.com/75mm-studio/security/commit/75c1108cc9f2d1bfc77b8bfa460c7b3652945a23#diff-24767bd051476e4b56d1487d90054046

https://github.com/75mm-studio/security/commit/de251caa6dc2d489d63fab245d9c4c308657da2a

**Comment by baesy0** [comment]
```
클라우드에 접속하는 클라이언트 계정이름도 동일한 코드네임을 사용합니다.
```
무엇과 동일한 코드네임인가요?

**Comment by baesy0** [comment]
```
프로젝트와 밀접한 관련이 있지만 정보가 없는 첫 방문자는 사진이 있는 신분증으로 신분확인을 합니다.
```
유효한 신분증에는 어떤 것들이 있나요?

**Comment by khw7096** [comment]
국가에서 지정한 신분증.(여권,주민등록증,운전면허증 이 있어요.)

해외에서 손님이 올 수 있기때문에.. 해외손님은 아마도 여권일듯해요.

**Comment by khw7096** [comment]
클라우드에 접속하는 클라이언트 계정이름도 동일한 코드네임을 사용합니다.

에 대한 질문을 좀더 구체적으로 적었어요.

https://github.com/75mm-studio/security/commit/9e37e8b3c92dc26ca18f0c50ec07cdcaa867a9f2

**Comment by khw7096** [comment]
신분증에 대한 구체적인 예시도 추가로 작성했어요.

https://github.com/75mm-studio/security/commit/58ed35d764c5e460ecbffef3777c6f534793a290

**Comment by khw7096** [comment]
클라우드 부분의 pr은 머징되었어요. 신분증 부분이 추가 번역완료되면 이 이슈를 닫을께요.

**Comment by khw7096** [comment]
해당 pr이 다 진행되어 이 이슈를 닫습니다.
