### ISSUE TITLE
보안사고 대응조치 문서 관련 이슈.

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#57]
1. 조세환님의 영문이름을 알려주세요

1. ```보안관계자(정), 보안관계자(부)```는 반장과 부반장 같은 건가요?

**Comment by khw7096** [comment]
네. 책임자. 부책임자 예요.

**Comment by khw7096** [comment]
세환님 이름은 알게되면 남겨놓을께요~

**Comment by khw7096** [comment]
SeHwan Jo

**Comment by khw7096** [comment]
이름을 영문으로 바꾸어 두었어요. 

https://github.com/75mm-studio/security/commit/b9be0aee84917620cf43a33f9e2b1cbd2afc86e8
