### ISSUE TITLE
NDA 문서 관련 이슈

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#62]
1. [임직원 정보 기록](https://github.com/baesy0/security/blob/NDA/docs/nda.md#%EC%9E%84%EC%A7%81%EC%9B%90-%EC%A0%95%EB%B3%B4%EA%B8%B0%EB%A1%9D-employer-information)에
``` 보안서약서 항목 변경 시 보안서약서를 갱신합니다```라는 부분이 있는데, 갱신 시 임직원에게 어떻게 알릴 지 추가되면 좋을 거 같아요.

1. [보안서약서 항목](https://github.com/baesy0/security/blob/NDA/docs/nda.md#%EB%B3%B4%EC%95%88%EC%84%9C%EC%95%BD%EC%84%9C-%ED%95%AD%EB%AA%A9nda-articles)의 ```첫 항목은 협력업체, 외부용역에만 표기함```에서 첫 항목이 의미하는 바가 무엇인가요?

1.  [방문협약이 불가능시](https://github.com/baesy0/security/blob/NDA/docs/nda.md#%EB%B0%A9%EB%AC%B8%ED%98%91%EC%95%BD%EC%9D%B4-%EB%B6%88%EA%B0%80%EB%8A%A5%EC%8B%9C) 기밀유지협약서를 보내는 측과 받는 측을 명확히 알려주시겠어요:)

**Comment by khw7096** [comment]
이 부분은 한글 문서를 조금 고치고 커밋링크를 남겨줄께요.

**Comment by khw7096** [comment]
각 항목에 대한 커밋입니다.

1. https://github.com/75mm-studio/security/commit/3c022b83733838a12e3c38fc963cc465f9d8e25d

2. https://github.com/75mm-studio/security/commit/38675cb47c72be1553bcf81d251efd184d68bd37

3. 상황에 따라 다릅니다. 클라이언트가 먼저 보낼수도 있고 75미리 스튜디오측에서 먼저 보낼 수 있어요. 프로젝트 진행에 따라서 명확하진 않아요.

**Comment by baesy0** [comment]
1,2번 참고해서 수정했습니다. 3번은 추후에 수정하고 PR할게요:)

**Comment by khw7096** [comment]
이 이슈도 닫겠습니다.
