### ISSUE TITLE
README.md문서 관련 이슈

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#65]
1. ```이 문서는 회사 구조의 변경, 업무장비, 서버장비, 네트워크 장비가 추가되어 보안이슈가 발생할 때마다 주기적으로 갱신됩니다.``` 에서 ```회사 구조의 변경```은 회사의 물리적 구조(사무실의 구조)인가요, 내부적인 구조인가요?

1. 최원준님의 영어이름을 알려주세요:)

**Comment by khw7096** [comment]
Won Jun Choi

https://github.com/75mm-studio/security/commit/b6d6df4b6e93222b6c1bcf67331172586572db8a

이름변경완료.

**Comment by khw7096** [comment]
물리적인구조(하드웨어,네트워크), 내부인력구조(담당자변경등) 둘다예요.

https://github.com/75mm-studio/security/commit/22da4c43abd4dfb2db653c27b27993921a8eab8f

내용을 좀더 구체화함.

**Comment by baesy0** [comment]
수정한 후 다시 PR했습니다:)

**Comment by khw7096** [comment]
이 이슈를 닫을께요.
