### ISSUE TITLE
[클라이언트 컴퓨터, 장비 정책]에서 '스토리지'의 해석

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/security#72]
1. [클라이언트 컴퓨터, 장비 정책](https://github.com/75mm-studio/security/blob/master/docs/clientpc.md#linux)문서에서 ```스토리지```는 클라우드의 의미로 쓰인게 맞나요? ```ex> 모든 데이터는 스토리지에 저장합니다``` ```ex>스토리지에 저장되는 데이터는 액세스 로그정책에 따라서 Log가 생성됩니다.```([클라우드컴퓨팅](https://github.com/75mm-studio/security/blob/master/docs/cloud.md#%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-logs--cloud-logs))
1. 클라우드와 스토리지가 같은 의미로 쓰이는 경우가 종종 있는 것 같은데 맞나요?
1. 만약 맞다면 용어를 ```클라우드```로 통일하려고 하는데 알맞은 용어인가요?

**Comment by khw7096** [comment]
스토리지는 데이터 저장 매체라서 클라우드랑은 달라요.

스토리지는.. storage 가 맞아용.

**Comment by khw7096** [comment]
이 이슈는 닫을께용.

**Comment by baesy0** [comment]
아항 넹넹!
