### ISSUE TITLE
회사이름을 코드명으로 한다.

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/security#85]

**Comment by khw7096** [comment]
https://github.com/75mm-studio/security/commit/f077ba365cc65a14782bdc2d093dfd9974281443

1차 변경완료.

**Comment by baesy0** [comment]
+2 영어까지 수정해주셨네요! 희희 감사해요

**Comment by khw7096** [comment]
어려운게 있거나 제가 잘못한게 있다면, 그때 체크해줘용.

**Comment by baesy0** [comment]
넹!
